repos:
- hooks:
  - id: ruff
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
- hooks:
  - id: commitizen
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.1
